title: ScamGuard
description: ScamGuard is the community-powered solution against scammers on Discord
author: The Antiscam Group
logo: /assets/site-logo.png
favicon: /favicon.ico
url: "https://scamguard.app"
google_analytics: "G-3B15EPXBFZ"
permalink: /:slug
comments: false
report:
  support_multiple_files: true
  max_size_per_file: 3
  max_files: 4
  max_size: 10
  turnstile_key: "0x4AAAAAAA7RsNNbQGiNcEUi" 
bot_name: ScamGuard
discord_client_id: 1152057650226401320
show_sidebar: false
hide_share_buttons: true
theme: bulma-clean-theme
force_theme: dark
footer_menu: footer_menu
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-liquify
  - jekyll-minifier

defaults:
  - scope:
      path: ""
    values:
      image: /assets/site-logo.png

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitattributes
  - .gitignore
  - .markdownlint.json
  - CNAME
  - README.md
  - .github/
  - LICENSE
  - node_modules/
  - package.json
  - package-lock.json
  - assets/webfonts/license.txt

jekyll-minifier:
  compress_css: false
  preserve_line_breaks: true