# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    # But ignore if the commit only updates these
    # paths
    paths-ignore:
      - ".github/dependabot.yml"
      - "README.md"
      - "LICENSE"
      - "CNAME"
      - ".gitignore"
      - ".gitattributes"
      - ".markdownlint.json"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      clear_cache:
          description: "Clear Cache"
          required: true
          type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Clean job
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    continue-on-error: true
    steps:
      - name: Cleanup Pages Deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
          onlyDeactivateDeployments: false
      - name: Cleanup Pages Actions
        uses: igorjs/gh-actions-clean-workflow@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          runs_to_keep: 1
          runs_older_than: 0
  # Build job
  build:
    needs: cleanup
    runs-on: ubuntu-latest
    outputs:
      cache_clear: ${{ steps.filter.outputs.clear_cache }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache Clear Check
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            clear_cache:
              - '**.md'
              - '!README.md'
              - '**.html'
              - 'assets/**'
              - '_data/**.yml'
              - '_config.yml'
              - 'Gemfile'
              - 'robots.txt'
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version: "24.11.1"
          package-manager-cache: true
      - name: Node Package Install
        run: npm install
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@v1.276.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Purge CSS
        if: success()
        # idk why but the output directory is much different than what it is on windows
        # this should fix all of it though
        run: npx purgecss -v -font --css assets/css/*.css --content "_site/*.html" --output _site/assets/css
      - name: Sanity check
        if: success()
        run: ls -lha _site/assets/css
      - name: Upload artifact
        if: success()
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v4

  # Deployment and cache clean job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Cloudflare Cache Cleaner
        if: needs.build.outputs.cache_clear == 'true' || inputs.clear_cache == 'true'
        uses: Cyb3r-Jak3/action-cloudflare-cache@v3.0.0
        with:
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

